### ISSUE TITLE
What's the _frame_prior for when calculated the oic loss?

### ISSUE THREAD

**Issue by JacobKong** [zhengshou/AutoLoc#4]
Dear author:

I read the code about oic_loss layer. I am wondering what's the purpose of _frame_prior when you select the most likely anchor per temporal position? 

Why don't you use the original score instead of calculating ref_score using following code?

> len_frame = inner_frames[1, :, x] - inner_frames[0, :, x]
>                         ref_scores = cur_scores * norm.pdf(len_frame, *cur_prior)
>                         a = np.argmax(ref_scores)

**Comment by JacobKong** [comment]
without frame prior, I got 21.6% map@tIoU=0.5 on THUMOS 14

**Comment by zhengshou** [comment]
Thanks for letting me know. We originally followed our SCNN work to use such prior knowledge for THUMOS dataset. It's good to know that such post-processing seems not necessary. BTW on AN we do not use such prior, following previous works as well.

**Comment by JacobKong** [comment]
My bad! It seems like the prior knowledge is quite important for the detection performance. 
I test again and now I can only get 8.7 map@tiou=0.5. Maybe I used the wrong settings before. 
I am still wondering what's the meaning of this prior? Can you tell me?

**Comment by zhengshou** [comment]
It's a common post-processing step performed on THUMOS in some action detection papers. Basically it is the prior knowledge about usually how long each action could be -- so that given a predicted action instance, a simple fitted Gaussian distribution tells us the probability of the certain action performing certain time duration, and we use this prob to multiply/refine the original predicted confidence score.

**Comment by JacobKong** [comment]
Now I am clear! Thanks for your reply!
